apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapiiot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapiiot
  template:
    metadata:
      labels:
        app: restapiiot
    spec:
      imagePullSecrets:
        - name: docker-secret  # Use the secret for pulling the private image
      containers:
        - name: restapiiot
          image: daksh-docker-release.arti.avl.com/avl/daksh/v1/main/tick:v1.0.13
          ports:
            - containerPort: 7000
              name: http-port-7000
            - containerPort: 3001
              name: http-port-3001
            - containerPort: 5001
              name: http-port-5001
            - containerPort: 5002
              name: http-port-5002
---
apiVersion: v1
kind: Service
metadata:
  name: restapiiot-service
spec:
  selector:
    app: restapiiot
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      name: http-port-7000
    - protocol: TCP
      port: 3001
      targetPort: 3001
      name: http-port-3001
    - protocol: TCP
      port: 5001
      targetPort: 5001
      name: http-port-5001
    - protocol: TCP
      port: 5002
      targetPort: 5002
      name: http-port-5002
  type: LoadBalancer
